basket=["Banana", "Apples", "Oranges", "Blueberries"]
print(basket)
basket.pop(0)
print(basket)
basket.remove("Blueberries")
print(basket)
basket.append ("Kiwi")
print(basket)
basket.append ("Apples")
print(basket)
basket.remove("Apples")
basket.remove("Kiwi")
basket.remove("Oranges")
basket.remove("Apples")
print(basket)

print("Finished!")